chore: streamline logging across modules
arcus-azure/arcus.scripting pull request #351
Opened 2022-12-26 06:05 UTC by stijnmoreels

Streamline logging and level across Powershell modules from `Arcus.Scripting.AzureActiveDirectory` to `Arcus.Scripting.LogicApps`, alphabetically.

Relates to #155

2022-12-26 09:44 UTC, pim-simons requested changes
Looking good 👍🏻 
We should probably also update the docs as the logging has changed, for example https://scripting.arcus-azure.net/Features/powershell/azure-logic-apps#disable-an-azure-logic-app states:
``` powershell
PS> Disable-AzLogicApp -ResourceGroupName "rg-common-dev" -LogicAppName "rcv-shopping-order-sftp"
# Access-token and subscriptionId retrieved
# Attempting to disable rcv-shopping-order-sftp

# Successfully disabled rcv-shopping-order-sftp
```

And that is not correct anymore after this PR.

2022-12-26 09:44 UTC, pim-simons commented on src/Arcus.Scripting.ActiveDirectory/Scripts/Add-AzADAppRoleAssignment.ps1
> +        Write-Host "Added role '$Role' to Active Directory Application '$($adApplication.DisplayName)e'"
```suggestion
        Write-Host "Added role '$Role' to Active Directory Application '$($adApplication.DisplayName)'"
```

2022-12-26 09:44 UTC, pim-simons commented on src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicAppsFromConfig.ps1
> +                        Write-Host "Check 'NoWaitingOrRunningRuns' executed successfully on Azure Logic APp '$logicApp'" -ForegroundColor Green
```suggestion
                        Write-Host "Check 'NoWaitingOrRunningRuns' executed successfully on Azure Logic App '$logicApp'" -ForegroundColor Green
```

2022-12-26 10:23 UTC, stijnmoreels commented
> We should probably also update the docs as the logging has changed,

Yes, I was thinking about that. Maybe we should not have the 'exact' logging in the docs as it would be rather hard/tedious to get them up-to-date all the time. Maybe we can only include a truncated version of information-like/successful messages?

2022-12-26 10:24 UTC, stijnmoreels commented on src/Arcus.Scripting.ActiveDirectory/Scripts/Add-AzADAppRoleAssignment.ps1
> +        Write-Host "Added role '$Role' to Active Directory Application '$($adApplication.DisplayName)e'"
Woops, what happened here 😅 , thx!

2022-12-27 07:21 UTC, pim-simons commented
> > We should probably also update the docs as the logging has changed,
> 
> Yes, I was thinking about that. Maybe we should not have the 'exact' logging in the docs as it would be rather hard/tedious to get them up-to-date all the time. Maybe we can only include a truncated version of information-like/successful messages?

I get your point, but I honestly quite like the way we have it setup in the docs right now, it shows you exactly what to expect which I really like.

2022-12-27 07:53 UTC, stijnmoreels commented
Now, it is updated with the full correct information/success messages.

2022-12-27 08:00 UTC, pim-simons approved these changes
Looks good to me 🥇

2022-12-27 08:05 UTC, merged