chore: sreamline loggging across modules 2
arcus-azure/arcus.scripting pull request #352
Opened 2022-12-26 08:19 UTC by stijnmoreels

Streamline logging and level across Powershell modules from `Arcus.Scripting.Management` to `Arcus.Scripting.Storage.Table`, alphabetically.

Relates to #155

2022-12-26 08:23 UTC, stijnmoreels commented on src/Arcus.Scripting.Sql/Scripts/Invoke-AzSqlDatabaseMigration.ps1
> +                              ") " +
Changed the tab characters to spaces.

2022-12-26 09:51 UTC, pim-simons requested changes
Great work again 👍🏻 
[As mentioned in the other PR](https://github.com/arcus-azure/arcus.scripting/pull/351#pullrequestreview-1229987141) we should probably also update the docs.

2022-12-26 09:51 UTC, pim-simons commented on src/Arcus.Scripting.Management/Scripts/Get-AzApiManagementSoftDeletedResources.ps1
> +Write-Verbose "Checking if the zure API Management service '$Name' is listed as a soft deleted service..."
```suggestion
Write-Verbose "Checking if the Azure API Management service '$Name' is listed as a soft deleted service..."
```

2022-12-26 09:51 UTC, pim-simons commented on src/Arcus.Scripting.Management/Scripts/Restore-AzApiManagementSoftDeletedService.ps1
> +    throw "Soft deleted Azure API Management serivce '$Name' could not be restored. Details: $($_.Exception.Message)"
```suggestion
    throw "Soft deleted Azure API Management service '$Name' could not be restored. Details: $($_.Exception.Message)"
```

2022-12-26 09:51 UTC, pim-simons commented on src/Arcus.Scripting.Management/Scripts/Restore-AzApiManagementSoftDeletedService.ps1
> +Write-Host "Successfully restored the soft deleted API Management service '$Name'"
```suggestion
Write-Host "Successfully restored the soft deleted API Management service '$Name'" -ForegroundColor Green
```

2022-12-27 08:00 UTC, pim-simons approved these changes
Looks good to me 🥇

2022-12-27 08:04 UTC, merged